apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argocd-example
  namespace: argocd-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args:
        - |
          cat <<EOF > /usr/share/nginx/html/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
              <style>
                  body {
                      background-image: url('https://i.ibb.co/qs2KqW2/wallpaperflare-com-wallpaper.jpg');
                      background-repeat: no-repeat;
                      background-size: auto;
                  }
                  h1 {
                      font-family: 'Press Start 2P', cursive;
                      font-size: 4.5rem;
                      position: absolute;
                      top: 50%;
                      left: 50%;
                      transform: translate(-50%, -50%);
                      text-align: center;
                      animation: colorchange 5s infinite;
                  }
                  img {
                      position: absolute;
                      top: 50px;
                      left: 50%;
                      transform: translateX(-50%);
                      width: 150px;
                  }
                  .developed-by {
                      position: absolute;
                      right: 10px;
                      bottom: 10px;
                      font-size: 1.2rem;
                      font-weight: bold;
                      color: rgba(255, 255, 255, 0.7);
                  }
                  @keyframes colorchange {
                      0% { color: #FFC107; }
                      14% { color: #FF9800; }
                      28% { color: #FF5722; }
                      42% { color: #E91E63; }
                      56% { color: #9C27B0; }
                      70% { color: #673AB7; }
                      84% { color: #3F51B5; }
                      100% { color: #FFC107; }
                  }
              </style>
          </head>
          <body>
              <h1>Hello! I'm "synced" by ArgoCD</h1>
              <img src="https://cncf-branding.netlify.app/img/projects/argo/icon/color/argo-icon-color.png" alt="ArgoCD Logo">
              <div class="developed-by">Developed by Süleyman Kütükoğlu</div>
          </body>
          </html>
          EOF
          cat <<EOF > /etc/nginx/conf.d/default.conf
          server {
              listen 80;
              location / {
                  root /usr/share/nginx/html;
                  index index.html;
              }
          }
          EOF
          nginx -g 'daemon off;'
